version: '3'

services:
  base:
    build: .

  # runs a server with the save hook
  jupyterfg-server:
    build: .
    ports:
      - 8886:8888
    command: jupyter lab

  # executes a notebook
  jupyterfg-execute:
    build: .
    volumes:
      - ./test:/test:rw
    environment:
      - STATUSUPDATEURL=http://host.docker.internal:5000/statusupdate
    command: python -m jupyterfg /test/notebooks/working.ipynb
