[build-system]
requires = ["flit"]
build-backend = "flit.buildapi"

[tool.flit.metadata]
module = "crash_ext"
author = "FASTGenomics Team"
author-email = "contact@fastgenomics.org"
requires=[
    "notebook",
]
